export const NOTIFICATION_POSITIVE_ADD = 'NOTIFICATION_POSITIVE_ADD';
export const NOTIFICATION_ERROR_ADD = 'NOTIFICATION_ERROR_ADD';
export const NOTIFICATION_REMOVE_BY_INDEX = 'NOTIFICATION_REMOVE_BY_INDEX';
